import Head from "next/head";

const CustomHead = ({ title }) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </Head>
);

CustomHead.defaultProps = {
  title: "Codeline Consulting",
};

export default CustomHead;
