import Head from "next/head";

const CusHead = () => (
  <Head>
    <title>Codeline Consulting</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </Head>
);

export default CusHead;
